timescale/timescaledb-docker-ha

.gitlab-ci.yml, CHANGELOG.md, Dockerfile, Makefile
As TimescaleDB 1.7 has been released, we can now support PostgreSQL 12,
after this commit, Docker images for PostgreSQL 11 and PostgreSQL 12
will be built during CI/CD.
To avoid name clashes the dummy container names now also include the
major PostgreSQL version.
=> Build PostgreSQL 12 images in CI/CD

Makefile
When publishing the Docker image, we may wish to push to (private)
registries, so allow an override.
=> Allow overrides for the publishing repositories

CHANGELOG.md, scripts/augment_patroni_configuration.py, scripts/post_init.sh
By default, Patroni will not restore a backup if no master can be found.
However, it may be a totally valid usecase to pause your deployment.
Therefore, we will allow bootstrapping to be done using the backup even
if no master is currently running.
Second, the race between the pgBackRest wrapper and initdb seemed to
have been a bit to tight, so allow 30 seconds instead of 10 seconds to
pass before bailing out on triggering a backup.
Third, a misconfiguration, as --stanza=demo never existed. As the
command was only used in the thus far never supported mode of bootstrap
without master, it never was an issue.
=> Backup improvements for restoring without a master

.gitlab-ci.yml, CHANGELOG.md, Dockerfile, Makefile, README.md, scripts/version_info.sql
- Introduce a few more ci/cd stages, so we can better control the
pipeline in GitLab.
- Ensure we can push to the docker.io registry for those images that
are to be published.
- Publish images when tag starts with a v, this removes the need to
manually create images.
- Drop the use of yaml anchors in favor of GitLab `extends`
- Default to PostgreSQL 12 instead of PostgreSQL 11
Some refactoring of the method of adding Docker Labels to the image, to
ensure every image has version information of the critical pieces it
contains.
tsdb_admin allows us to restrict the scope of CREATEROLE/CREATEDB users.
It needs to be explicitly configured in the shared_preload_libraries
before it will be used, adding this therefore does not intervene with
any existing deployments.
=> build tsdb_admin, tsdb_prometheus, and publish images

CHANGELOG.md
* Include `psutils` to allow some process troubleshooting inside the container
* Include custom timescaledb scripts for pgextwlist
* `lz4` support, which can be used by pgBackRest
* `tsdb_admin` can be included in the image
* `timescale_prometheus` is now included in the image
* GitLab CI/CD will now publish Docker images to Docker hub on version tags
=> Release v0.2.13

.gitignore, scripts/timescaledb/after-create.sql
To enable seamless restores for our users on Forge, we need to grant access to internal timescale schema and tables to the database owner.
=> Add grants to internal timescale schemas

CHANGELOG.md, Dockerfile
Adding pgBouncer adds a very few amount of bytes, but does allow us to
use the same Docker Image in some setups that have a sidecar pgBouncer
container, or a separate pod.
=> Include pgBouncer in the Docker Image

CHANGELOG.md, Dockerfile
By installing the latest stable (1.7.4) after installing 2.0.0-rc2 we
accomplish that the Docker Image *does* contain the 2.0.0-rc2 libraries,
but they are not the default version for Timescale.
=> Include 2.0.0-rc2 libraries

Dockerfile
Our previous implementention would fail for custom git revisions,
basically blocking any custom commit from being built against PostgreSQL
12.
By explicitly ignoring only versions 1.6.x for PostgreSQL 12, we do have
the ability to add a custom git reference in the list of versions to be
built, allow easier ways of Docker Image testing.
=> Verify version compatibility using substring

CHANGELOG.md, Dockerfile
For completeness, we also include 2.0.0-rc3 and 2.0.0-rc4, as we would
otherwise force those users that upgraded to a Release Candidate to
immediately upgrade after this Docker Image is used.
=> Include TimescaleDB 2.0.0

CHANGELOG.md, Dockerfile
By compiling the 2.0.0 version last we ensure it becomes the default
version when installing `CREATE EXTENSION timescaledb`
=> Default to TimescaleDB 2.0.0

.gitlab-ci.yml
This is required to activate a Gitlab runner. Previously, Gitlab still
ran the job even without a matching tag, but that no longer works.
=> Add "docker" tag to builder job

Dockerfile
Add extensions:
- pg_logerrrs to export SQL errorcodes/counts in the database view
- pg_auth_mon to monitor/count connection atttempts
=> Improve monitoring of errors and connections

CHANGELOG.md, Dockerfile
PostgreSQL released security updates recently,
this will ensure our Docker Images will contain
PostgreSQL 11.11 and 12.6
TimescaleDB has had a patch release: 1.7.5.
Some new extensions
=> Stamp release 0.3.3

CHANGELOG.md, Dockerfile, Makefile
By default, the directories supporting extensions and their files are
owned by root, and are readable by PostgreSQL.
This is (in general) a good thing: It ensures that these files cannot be
updated, not even if an end-user has access to the `superuser` of the
PostgreSQL cluster.
This does however prevent *any* live patching of these directories being
done on a live container, the container itself is running as a
non-privileged container in most environments, and therefore no files
can be added. This means that any change - even adding an extension
version - requires the container to be stopped and started using a
different Docker Image.
By allowing the *addition only* of new files to the directories by the
PostgreSQL user, we open up some Development opportunities, without
causing to many …
=> Allow extensions to be added to a live container

Dockerfile
This allows overwriting of the libraries and sql files belonging to this
extension by the postgres user.
=> Make postgres own the timescale-analytics files

.github/workflows/publish_image.yaml, Dockerfile, Makefile
With this commit in, we can build Docker Images containing all the
software we need for PostgreSQL 13.
To make this work, we needed to fix a few things:
* `pg_auth_mon`: Bump tag to a PostgreSQL 13 supported version
* `timescale_analytics`: Only build PostgreSQL <version> and be explicit about
the version when using `cargo pgx`, to avoid rust compilation
errors.
* `timescaledb`: Ensure we only build 2.1+ for PostgreSQL 13
PostgreSQL 11 is not yet deprecated with this commit in, however both
the Makefile and GitHub Actions no longer build PostgreSQL 11 images.
=> PostgreSQL 13 - Soft deprecation of 11 images

CHANGELOG.md
Bump from 0.3 to 0.4, as we deprecate PostgreSQL 11 and now include
PostgreSQL 13
=> Stamp v0.4.0

Dockerfile
Having these tools available in the Image themselves simplifies many
debugging situations, whereas the cost of adding these to the Image is
measured in kB's.
=> Include gdb and gdbserver

Dockerfile
https://github.com/powa-team/pg_stat_kcache is an extension that can
keep track of many system level metrics for us. It requires to be added
to the `shared_preload_libraries` to be useful.
=> Add pg_stat_kcache libraries

CHANGELOG.md
* `gdb` and `gdbserver` to aid in debugging
* [pg\_stat\_kcache](https://github.com/powa-team/pg_stat_kcache) extension: Gathers statistics about real reads and writes done by the filesystem layer
* Label Docker Image with all minor PostgreSQL versions
=> Stamp release 0.4.5

CHANGELOG.md
* `hot_forge`: A private Timescale Project allowing hot patching of containers
* Bump `timescale_analytics` to 0.3.0
* Make all compiled extensions owned by `postgres`: Allows hot-patching
* `sqlite_fdw`: The potential use case switched to using `file_fdw`
=> Stamp release 0.4.7

Dockerfile
- jq is very useful in its interaction with pgbackrest --output json
- strace and procps are very useful for troubleshooting issues,
this happens infrequently, but if it does happen, it is invaluable to
have the tools available
- less is useful to read through some log files that get created, an
example is pgbackrest async logs may grow big and may only exist
inside the container
=> Mark certain tools as required

CHANGELOG.md, Dockerfile
Includes downgrade scripts for compatible TimescaleDB releases
=> Release version v0.4.13

Dockerfile
pg_auth_mon and logerrors Makefile doesn't support overriding PG_CONFIG,
use PATH to switch between major PostgreSQL versions.
=> Fix building some extensions for non-default Postgres version.

Dockerfile
Before this commit, the rust installation that would build all rust
components of this Docker against the latest stable compiler of Rust.
A newer stable rust compiler may (and has previously) cause
compiler/test/clippy warnings that may fail a build of one of our Rust
components altogether.
As Rust releases are out of our control, it seems wise to fix the Rust
version to a specific one, so we can explicitly move to a newer version
if required.
=> Fix Rust Version

.github/workflows/build_image.yaml, Dockerfile
This significantly reduces the time to build a Docker Image
=> Include prebuilt Hot Forge binary

.github/workflows/build_image.yaml, .github/workflows/publish_image.yaml, CHANGELOG.md, Dockerfile, Makefile
This commit reverts 3038c51ad72a1658688834c014d697fdd3b65778, however
the hot-forge tool no longer is built, it is downloaded.
=> New Image including Hot Forge

.github/workflows/build_image.yaml, .github/workflows/publish_builder.yaml, .github/workflows/publish_image.yaml, CHANGELOG.md, Dockerfile, Makefile, README.md
To allow us to use specific glibc 2.33+ features, we need to find a way
to run glibc 2.33. Running multiple glibc versions inside the same
container is something we'd like to avoid, we've seen multiple glibc
related bugs in our lifetime, adding multiple glibc versions in the mix
would make debugging harder.
Debian (and rust:debian) has served us well, however even Debian's
latest release (bullseye, August 2021) cannot give us glibc 2.33.
Ubuntu however does give us glibc 2.33 - as Ubuntu is based upon Debian
the changes required are not that big for this Docker Image. Most of the
tools we use will be the same across the board, as most of our tools our
installed using external repositories.
Some significant changes to get here are required though:
There was some (valid) criticism[1], …
=> Use Ubuntu as a base for our Docker Image

CHANGELOG.md
This is a major release, as the base Docker Image has changed from Debian to Ubuntu.
Our tests have not yet shown any issues with this update. We would advice anyone
that consumes these images to test that the new images also work for them in their
environment.
As this Docker Image has been in production for a while, it seems awkward to still not
be on version 1.0.0+, therefore, we mark this occasion with releasing version 1.0.0.
=> Release version 1.0.0

Dockerfile
For running integration tests with this Docker Image, it is very useful
to have no external dependencies, therefore having the option to run
native Raft for Patroni is very valuable.
https://patroni.readthedocs.io/en/latest/README.html#technical-requirements-installation
=> Include pysyncobj to support Patroni Raft mode

CHANGELOG.md
Minor PostgreSQL upgrades have been stamped [13](https://github.com/postgres/postgres/commit/084346ccee8ead6b387a90cdf6a29036ae9ec77e) [12](https://github.com/postgres/postgres/commit/8a94efd9bb71c2d5473836ce4899aedb9b4cfb2e) in the repo and should be available somewhere on November 11th.
We should therefore not merge this PR before those releases are available in the Ubuntu repositories.
* PostgreSQL [12.9](https://www.postgresql.org/docs/12/release-12-9.html) and [13.5](https://www.postgresql.org/docs/13/release-13-5.html) have been released
* Include dependencies to support native Raft support for Patroni [PySyncObj](https://github.com/bakwc/PySyncObj)
=> Stamp release v1.0.8

.github/workflows/publish_image.yaml, Dockerfile
The 13 images still contain the PostgreSQL 12 binaries, so this change
only affects those that are still running PostgreSQL 11 only
=> Only publish PostgreSQL 13 images from now on

.github/workflows/build_image.yaml, .github/workflows/publish_builder.yaml, .github/workflows/publish_image.yaml, Dockerfile, Makefile, build_scripts/install_timescaledb-toolkit.sh
This ensures that all new installations will be on toolkit 1.5.1 or
higher, current deployments that have Toolkit < 1.5.1 installed will
continue to work, this only affects new installations or upgrades to
versions < 1.5.1
=> Build TimescaleDB Toolkit 1.5.1 from private repo

CHANGELOG.md, Dockerfile
The https://ubuntu.com/about/release-cycle informs us that support for
Ubuntu 21.04 has ended, and we should therefore upgrade to a newer
Ubuntu release.
=> Use Ubuntu 21.10 as a base for our Docker Image

.github/workflows/build_image.yaml, .github/workflows/publish_builder.yaml, .github/workflows/publish_image.yaml, Dockerfile
This is basically a revert of commit 922657d6, which was needed to
include a security fix that wasn't part of the public repository yet.
=> Build TimescaleDB Toolkit from public repo again

.github/workflows/build_image.yaml, .github/workflows/publish_builder.yaml, .github/workflows/publish_image.yaml, CHANGELOG.md, Dockerfile
Changed
* Include and default to [TimescaleDB 2.6.1](https://github.com/timescale/timescaledb/releases/tag/2.6.1)
* Include Cloudutils v1.1.2
=> Stamp release v1.2.3

Dockerfile
This `timescaledb-docker` commit breaks `timescaledb-docker-ha`
https://github.com/timescale/timescaledb-docker/commit/9a5d6db57e34a971d3c44898d5513d74481e27f5
=> Fix GITHUB_TIMESCALEDB_DOCKER_REF

.github/workflows/build_image.yaml, .github/workflows/publish_image.yaml
Even though the pg14 and pg13 images can be used for pg12 deployments
when setting a sane PATH, some users would like to have a tagged pg12
release as well.
As we build these images in parallel, it seems ok to keep publishing
pg12 alongside the pg13 and pg14 images.
=> Publish tagged pg12 images

.github/workflows/build_image.yaml, .github/workflows/publish_image.yaml, Dockerfile, Makefile
- Related to https://github.com/timescale/patroni/pull/1
=> Add Patroni updates for new static_primary config option

Dockerfile
Ubuntu's repositories are updated more often than their docker images are, so this can sometimes
install security fixes that might otherwise be missed.
For example, today while I was testing the build of timescale 2.7.0 there was a libpcre vulnerability that was fixed in the ubuntu repository, but not in the base image, so the result was the image I created was still affected.
=> Add apt-get upgrade

CHANGELOG.md
Patroni was released already, however we need to wait a bit for the debian packagers to make it available to us.
=> Patroni 2.1.4

CHANGELOG.md
Reverts timescale/timescaledb-docker-ha#281
As 1.4.7 was already tagged in a previous commit, I'll temporarily revert this before we decide how we proceed from here.
We need to either stamp 1.4.8 and update the changelog retroactively or something else.
Waiting on input from the team.
=> Revert "Stamp 1.4.7"

Dockerfile
Update Patroni to `2.2.0-beta.5` and add in fix for log spamming with `403` when trying to create a Kubernetes service
Issue: https://github.com/timescale/helm-charts/issues/405
=> Update patroni, add fix for creating k8s svc

scripts/tsdbadmin.sql
Both log_min_duration_statement and pg_stat_statements.track_utility may cause an `ALTER USER john WITH password 'strong'` to show up in postgresql diagnostic logs, or in the pg_stat_statements view.
Adding these settings to the function ensures they will no longer show up there.
=> Reduce chance of leaking passwords

.github/workflows/build_image.yaml, .github/workflows/publish_compiler.yaml, .github/workflows/publish_image.yaml
Github switch ubuntu-latest to 22.04, so we might as well come along.
This also uses a better GH token for pushing to docker hub, and updates the docker login
action to remove some warnings.
=> Switch GH token and update ubuntu base image

docker-entrypoint.sh
On Windows (or other filesystems that don't like chown/chmod) this might not work, but that doesn't mean we don't want to try to execute postgres.
Hopefully fixes #334
=> Don't fail if we can't chown/chmod

Dockerfile
There's a signature verification problem after Feb 1 due to SHA-1
https://blog.rust-lang.org/2023/02/01/Rustup-1.25.2.html
=> Update rustup to 1.25.2

Dockerfile
As pgvector assumes running on the same system it was build at, and this image may run on a wide variety of instances with different CPUs, we have to disable CPU specific instruction optimization. See https://github.com/pgvector/pgvector/issues/130
=> Build pgvector with OPTFLAGS=""

Dockerfile, Makefile
Since DCS failsafe has been merged into Patroni v3, there is no need for custom-patching it. Moreover, our own branch reverts some changes expected in v3, namely, changes a primary_start_timeout parameter name back to master_start_timeout.
=> Remove DCS failsafe Patroni fork

Dockerfile, Makefile
This reverts commit e63fa16bc82610a9a90d2d9f6e4607c030293839.
Downstream has been fixed for patroni 3.x
=> Revert "Revert "Remove DCS failsafe Patroni fork (#394)" (#397)"

build_scripts/install_extensions, build_scripts/shared.sh, build_scripts/shared_install.sh, build_scripts/shared_versions.sh, build_scripts/versions.yaml
This also adds support for the renamed pgx -> pgrx from version 0.8.0+, and also removes the default-cargo-pgx key in versions.yaml since almost every extension version needs a different version anyway.
This automatically picks using pgx or pgrx based on the requested version.
=> Add toolkit 1.17.0

Dockerfile
Use the same style as the rest of the Dockerfile and simplify the use of dpkg --print-architecture, removing the remaining embedded amd64 statements.
=> Simplify pgbouncer_exporter installation

Dockerfile
We do `git reset HEAD --hard`, but it doesn't remove untracked files,
making a subsequent builds a no-op. Since we want to actually build
an extension anew for different postgres versions, run `make clean`.
=> Run make clean in some extensions

Dockerfile
`Make` without `all` doesn't build pgvector extension installation script, resulting in an error when attempting to install it.
Move `git reset` outside of the loop for postgres versions, as we `make clean`, one need to reset it only once in the beginning, in case we have work directory cached from another run.
=> Run make all for pgvector

build_scripts/versions.yaml
Build TimescaleDB 2.13.1 
https://github.com/timescale/timescaledb/releases/tag/2.13.1
=> Configure 2.13.1 build

Dockerfile
This also adds a bit more context to the problem.
https://salsa.debian.org/postgresql/postgresql/-/commit/b995beb3cd1c2b8834605007227b3cedab6462e4 says that this is required only for testing, so I think we're safe to use the current work-around. The previous tzdata file isn't available anymore, but one older file is still around. If the old tzdata file disappears too, we'll have to do something more drastic.
This should fix #448
=> Use an older tzdata file that's still available

.github/workflows/build_branch.yaml, .github/workflows/publish_images.yaml, Makefile, build_scripts/shared_versions.sh, build_scripts/versions.yaml, cicd/shared.sh
This uses the closed beta for linux/arm64 runners from github. Until they become generally available, the image used for the runners is missing _many_ tools (like make?!). This adds a step to install docker and build-essential (that includes make) when building the arm images.
There's also one commit that will be dropped before merging, and the timescaledev docker hub reference would be changed to just timescale as well.
=> arm64 builds!

Dockerfile
In #442 I added the `python3-barman` package in anticipation for the `ImageCatalog` feature in CloudNativePG that would allow running the official Timescale image in CNPG.
That PR though has two issues:
1. Unlike `python-pip`, `apt-get` does not install package binaries, required for interaction with `barman-cloud`.
2. It did not add necessary dependencies for Azure and Google cloud support.
I tried implementing it without `python-pip`, but the Azure Storage package `python3-azure-storage` is over `600MB` which completely defeats the purpose of the size optimization. With `pip` the `barman` package only fetches `azure-blob-storage` and this results in around `300MB` smaller image, compared to the deb package only approach.
I suspect that once I add `python3-pip` it may be beneficial for …
=> Bug Fix: Missing Barman Cloud entrypoints

build_scripts/versions.yaml
Per https://github.com/timescale/timescaledb/releases/tag/2.15.2
=> Build TimescaleDB 2.15.2

build_scripts/versions.yaml
Include and default to TimescaleDB 2.15.3
=> Release TimescaleDB 2.15.3

build_scripts/versions.yaml
https://github.com/timescale/timescaledb/releases/tag/2.16.0
=> Release timescaledb 2.16.0

build_scripts/versions.yaml
https://github.com/timescale/timescaledb/releases/tag/2.16.1
=> Release timescaledb 2.16.1

Dockerfile
This brings the vectors.so file from 450mb to 12mb.
=> Strip vecto.rs's .so file

docker-entrypoint.sh
Wait for permissions to be set just prior to initdb. This fixes being unable to use `--user` with docker to specify a different UID.
=> Make sure to wait for permissions to be set

build_scripts/versions.yaml
https://github.com/timescale/timescaledb/releases/tag/2.18.0
=> Release TimescaleDB 2.18.0

Dockerfile
The latest pg12 packages contain a Build-Depends on an as-yet unreleased
package: postgresql-common-dev. This package should be released in mid
Febrary 2025. In the meantime we work around this by creating an empty
package.
See: https://www.postgresql.org/message-id/flat/D6BD9F9D-8DBE-4E0B-B00A-2130E7C6385D%40guthrie.ch
=> fix pg12 build

Dockerfile
pgai's `build.py install` will automatically use uv if it's available on the system path. When uv installs dependencies into a target directory, it uses hardlinks to a centralized cache. This allows a large number of dependencies to be reused across pgai versions.
=> Use uv to install pgai dependencies

.github/workflows/publish_images.yaml, Dockerfile
This also re-enables our scheduled builds that were disabled due to the previous pg release that broke ABI compatibility.
=> Drop postgresql-common-dev fix due to the new releases

Dockerfile, build_scripts/pg_version.sh, build_scripts/versions.yaml
This PR pins the Postgres versions installed.
> [!NOTE]  
> I didn't bother about the build dependencies. Since it is not common to change dependencies on minor releases, I'm assuming that it is safe to use the latest minor to define the build deps.
Main changes in the PR:
* All versions are set in the `build_scripts/versions.yaml` file
* Added the PGDG archive repo
=> pin pg versions

build_scripts/versions.yaml
This [was released](https://github.com/timescale/pgvectorscale/releases/tag/0.6.0) on Friday last week.
=> Add vectorscale 0.6.0

build_scripts/versions.yaml
Even the latest toolkit is compatible with v12, which is now obsolete,
so there is no reason to keep older versions, freeing 639MB from the target image
(credits to @feikesteenbergen  for the data points).
=> Get rid of old timescaledb_toolkit versions

Dockerfile, Makefile, README.md, build_scripts/shared.sh, build_scripts/versions.yaml, docker-entrypoint.sh
It's no longer supported, and won't get any further updates. If you need to upgrade from pg12, use a previous tag of this repository to perform the upgrade prior to switching to the newest builds.
=> Remove pg12

build_scripts/versions.yaml
https://github.com/timescale/timescaledb/releases/tag/2.19.1
=> Build TimescaleDB 2.19.1

build_scripts/versions.yaml
Related with https://linear.app/timescale/issue/ORC-31/add-new-issue-to-update-versions-after-recent-release
This pull request updates the PostgreSQL versions in the `build_scripts/versions.yaml` file to reflect the latest patch releases. These updates ensure compatibility with the most recent security and bug fixes.
Version updates:
* Updated PostgreSQL versions:
- `17` from `17.4` to `17.5`
- `16` from `16.8` to `16.9`
- `15` from `15.12` to `15.13`
- `14` from `14.17` to `14.18`
- `13` from `13.20` to `13.21` (`[build_scripts/versions.yamlL30-R34](diffhunk://#diff-c0b890f2279e6133d9571ea714e31f3fd24de4a888e0aaf595bd976f51aca419L30-R34)`)
=> Update PostgreSQL versions to 17.9 and others

build_scripts/versions.yaml
We released [pgvectorscale 0.7.1](https://github.com/timescale/pgvectorscale/releases/tag/0.7.1) yesterday.
=> Add vectorscale 0.7.1

build_scripts/versions.yaml
This PR adds the new release [2.20.1](https://github.com/timescale/timescaledb/releases/tag/2.20.1) to the public docker image.
- [Releases Calendar](https://docs.google.com/spreadsheets/d/1MgRDRPq_BXrFzInVfcjmce6Qlpawoyc3XNakfwJpe6s/edit?pli=1&gid=0#gid=0)
- [Slab doc with instructions](https://timescale.slab.com/posts/deploying-a-new-timescale-db-extension-version-odw7b3br).
- [Slack thread](https://iobeam.slack.com/archives/C08EEJXQDLK/p1748353008934059)
- Example of [previous PR](https://github.com/timescale/timescaledb-docker-ha/pull/548) in this repo.
=> add timescaledb 2.20.1

build_scripts/versions.yaml
Emergency release of tsdb [v2.20.2](https://github.com/timescale/timescaledb/releases/tag/2.20.2).
=> add timescaledb 2.20.2

Dockerfile, build_scripts/shared_install.sh
Make sure that arm and amd64 have the same features hashing when compiling timescaledb.
=> Require UMASH support and compile on ARM with +crypto

Dockerfile
A bug here caused pgai to be build on earlier versions.
Since it is incompatible with p15 and earlier, it caused the migrations running on those services to fail.
=> Fix a logical condition when build pgai

build_scripts/versions.yaml
- PostgreSQL 17.5 → 17.6
- PostgreSQL 16.9 → 16.10
- PostgreSQL 15.13 → 15.14
- PostgreSQL 14.18 → 14.19
- PostgreSQL 13.21 → 13.22
**Issues**
Closes https://linear.app/tigerdata/issue/PLA-48/add-latest-pg-minor-versions
=> Update PostgreSQL versions to latest patch releases

build_scripts/versions.yaml
This commit adds tsdb 2.21.4.
----
This pull request updates the `build_scripts/versions.yaml` file to add support for TimescaleDB version 2.21.4, specifying its compatibility with PostgreSQL versions 15 through 17.
Dependency version update:
* Added TimescaleDB version `2.21.4` to the list of supported versions, with `pg-min` set to 15 and `pg-max` set to 17.
=> add tsdb 2.21.4
