timescale/timescaledb-docker-ha

CHANGELOG.md
scripts/timescaledb/after-create.sql
scripts/timescaledb/after-update.sql

These custom scripts - if configured - can be used to run after a
pgextwlist allowed extension is created.
https://github.com/dimitri/pgextwlist#custom-scripts

Include custom after install/update scripts

---

CHANGELOG.md
Dockerfile

This allows us to use lz4 compression for pgBackrest

Include lz4

---

CHANGELOG.md
Dockerfile

The only addition is inclusion of Timescale 2.1.0

Stamp release 0.3.4

---

Dockerfile

By installing rust componenents in /build we simplify the cleanup, as
well as leave the door open for reuse by non-root users. (This is a
planned feature).
Using a minimal profile seems sane for ci/cd, no need to pull in the
world when only compiling our tools.

Tweak rustup installation

---

Dockerfile

In passing, remove a previous bugfix for PostGIS installation.
Fixes issue #101

Include pg_repack and hypopg

---

CHANGELOG.md
Dockerfile

Feike/release 2.2.1

---

.github/workflows/build_image.yaml
.github/workflows/publish_image.yaml
CHANGELOG.md
Dockerfile

We skip a few tags in the changelog, as they were created to test a few things with the build process, don't want to reuse those tags.

Feike/ts 2.3.1

---

CHANGELOG.md
Dockerfile

PostgreSQL minor releases only

Stamp 0.4.18

---

Dockerfile

Use correct asset id for fetching hot forge

---

Dockerfile

Add pl_debugger / pldbgapi plugin

---

.github/workflows/build_image.yaml
.github/workflows/publish_builder.yaml
.github/workflows/publish_image.yaml
CHANGELOG.md

Sorry for the noise in the CHANGELOG, it was autoformatted in a separate commit, but I thought it wouldn't hurt to keep it in.

Install cloudutils v1.1.1

---

CHANGELOG.md

Stamp v1.1.7

---

Dockerfile

Add pg_top

---

.github/workflows/build_image.yaml
.github/workflows/publish_compiler.yaml
.github/workflows/publish_image.yaml
CHANGELOG.md

Includes `create_certificate` idempotency changes.

Update cloudutils to v1.1.6

---

CHANGELOG.md

Stamp v1.4.2

---

CHANGELOG.md

Based on this https://www.postgresql.org/developer/roadmap/, that will be released today

pg 14.5 and 13.8

---

CHANGELOG.md

Upgrade to the new minor PostgreSQL versions
Fill-in changelog for v1.5.14 and v1.5.13

Stamp v1.5.15

---

.github/workflows/publish_image.yaml

Fix a couple missing images

---

Dockerfile
Makefile

This reverts commit fd7b8511816d74852ef931fd631a0f6abb0b90ab.

Revert "Remove DCS failsafe Patroni fork (#394)"

---

Dockerfile

The functionality have been removed, sans this reporting line.

Remove last traces of the DCS_FAILSAFE mode

---

Dockerfile
Makefile

this PR adds the [pgbouncer-exporter](https://github.com/prometheus-community/pgbouncer_exporter) to the docker image.

add pgbouncer exporter

---

Dockerfile
build_scripts/patroni_issue_2837.patch

For details, see https://github.com/zalando/patroni/issues/2837

Make _write_status a noop for Patroni

---

.github/workflows/publish_images.yaml

to Publish cloud images workflow
For Issue : https://github.com/timescale/eng-database/issues/513

Dispatch HA image published event

---

build_scripts/versions.yaml

This is a version that can also be built against PostgreSQL 16

Add toolkit 1.18.0

---

build_scripts/versions.yaml

https://github.com/timescale/timescaledb/releases/tag/2.14.0

Include timescaledb 2.14.0

---

Dockerfile

Added Barman Cloud for CloudNativePG compatibility

---

build_scripts/versions.yaml

Commit for issue https://github.com/timescale/eng-database/issues/584

Add timescaledb 2.14.2

---

Dockerfile
build_scripts/shared_versions.sh

this PR adds the pgsodium extension.

add pgsodium extension

---

build_scripts/versions.yaml

Commit for issue https://github.com/timescale/eng-database/issues/612

Add timescaledb 2.15.0

---

Dockerfile
cicd/shared.sh

We only want to support the pgai extension on postgres version 16 or greater.

Only support pgai on pg16+

---

Dockerfile

See: https://github.com/docker-library/postgres/issues/714
Fixes #492

Set STOPSIGNAL to SIGINT

---

build_scripts/versions.yaml

pg17 coming soon, but separately.

Initial build with 2.17.0

---

build_scripts/versions.yaml

https://github.com/timescale/timescaledb/releases/tag/2.17.1

Timescaledb 2.17.1

---

Dockerfile
Makefile

Adds pgai extension version 0.4.0

pgai version 0.4.0

---

build_scripts/versions.yaml

https://github.com/timescale/timescaledb/releases/tag/2.17.2

Timescaledb 2.17.2

---

build_scripts/versions.yaml

This PR adds the new Postgres minor version released on February 20th.

postgres 17.4 and others

---

build_scripts/versions.yaml

https://github.com/timescale/timescaledb/releases/tag/2.19.2

Add timescaledb 2.19.2

---

build_scripts/versions.yaml

Include TimescaleDB toolkit 1.21

---

Dockerfile

Certain files in the postgres lib and extension directories are owned by postgres:postgres to allow hot-patching of these files inside a container.
This wasn't true yet for pgai, by moving the pgai build commands into the block done by USER postgres, we should have files owned by postgres:postgres

Ensure pgai files are owned by postgres

---

build_scripts/versions.yaml

https://github.com/timescale/timescaledb/releases/tag/2.20.0

Add timescaledb 2.20.0
